### PR TITLE
update extension build + new images

### PR DESCRIPTION
**Pull request by terinjokes**
Begin to modernize Claire by updating the build process to build bundles in a dist directory, and removing vendored files from the repository.

Also adds two promotional images for the Chrome Web Store, and corrects the casing of "Cloudflare" throughout the extension.

### CODE REVIEW

**Comment by ram-nadella** [comment]
Is there a build step that needs to be run now before we release? (aka upload to Chrome Webstore?)

**Comment by terinjokes** [comment]
@ram-nadella Yes. `yarn install && yarn run build`. I can update the README.

**Comment by ram-nadella** [comment]
@terinjokes looks good!

Ran into a minor issue – for some reason the icon doesn't seem to change state when I go to `cloudflare.com` – just shows the default grey cloud without the dots at the bottom... wonder what's going on.

Also, good note about loading the extension from `dist` instead of `source`

Good to merge/release if the `cloudflare.com` issue is known / NBD.

**Comment by terinjokes** [comment]
@ram-nadella Yeah, that's interesting. Looks like it's been broken since dfc41d17bcd75bfa8f50f084b67c66e307c1d899, since we don't know what IP address the site was served over.

There's probably a better way to handle this than doing nothing. I'll fix in the next version.

**Pull request merged**
